### ISSUE TITLE
Broken for Node.js

### ISSUE THREAD

**Issue by onoranzefunebricloud** [lucavandro/CodiceFiscaleJS#20] opened 2019-06-06 16:59 UTC
Using `"codice-fiscale-js": "^2.2.1",`
```
ReferenceError: window is not defined
    at Object.<anonymous> (/..../node_modules/codice-fiscale-js/dist/codice.fiscale.umd.js:1:208)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/andrea.falzetti/dev/ofc/lambda-codice-fiscale/lib/functions/generaCodiceFiscale.js:9:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at AwsInvokeLocal.invokeLocalNodeJs (/..../serverless/lib/plugins/aws/invokeLocal/index.js:501:33)
```

Using `npm i codice-fiscale-js@2.1.0` works.

**Comment by lucavandro** [comment] 2019-06-26 23:35
thank you for your report. The issue is now fixed. Please upgrade to v2.2.3

**Closed** 2019-06-27 06:41 UTC
