### ISSUE TITLE
Validation is case sensitive

### ISSUE THREAD

**Issue by mbilotta** [lucavandro/CodiceFiscaleJS#21] opened 2019-06-13 17:01 UTC
Bug is here:

https://github.com/lucavandro/CodiceFiscaleJS/blob/520533431d73e51b1550454780f5fe6927aa9b07/src/codice-fiscale.js#L78-L84

Check fails because you're giving away the uppercase codice fiscale at line 83.

I'd rewrite that piece like this:
```typescript
let cf = codiceFiscale.toUpperCase();
if (cf.length !== 16) { 
   return false 
}
const expectedCheckCode = cf.charAt(15);
return CodiceFiscale.getCheckCode(cf.slice(0, 15)) === expectedCheckCode 
```

**Comment by lucavandro** [comment] 2019-06-26 22:38
thank you for your report. The issue is now fixed. Please upgrade to v2.2.2

**Closed by lucavandro** 2019-06-26 22:38 UTC
